# Generated by Django 2.1.1 on 2019-07-16 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20190715_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='activity_rules',
            field=models.ForeignKey(on_delete=False, to='goods.Activity', verbose_name='活动'),
        ),
    ]
