# Generated by Django 2.1.1 on 2019-07-16 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20190716_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='activity_rules',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Activity', verbose_name='活动'),
        ),
    ]
