# Generated by Django 2.1.1 on 2019-07-16 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20190716_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='activity_rules',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='goods.Activity', verbose_name='活动'),
        ),
    ]
