# Generated by Django 2.1.1 on 2019-07-18 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_auto_20190716_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='total_num',
            field=models.IntegerField(default=30, help_text='可砍刀数', verbose_name='可砍刀数'),
        ),
        migrations.AddField(
            model_name='ordergoods',
            name='total_num',
            field=models.IntegerField(default=30, help_text='可砍刀数', verbose_name='可砍刀数'),
        ),
    ]
