# Generated by Django 2.1.1 on 2019-07-18 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_auto_20190718_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='total_num',
        ),
        migrations.RemoveField(
            model_name='ordergoods',
            name='total_num',
        ),
    ]
