# Generated by Django 2.1.1 on 2019-08-05 09:36

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_auto_20190718_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='activity',
            field=tinymce.models.HTMLField(),
        ),
    ]
