# Generated by Django 2.1.1 on 2019-08-19 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_auto_20190805_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='command_str',
            field=models.CharField(blank=True, help_text='核销口令', max_length=32, null=True, verbose_name='核销口令'),
        ),
    ]
