# Generated by Django 2.1.1 on 2019-08-19 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0009_goods_command_str'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='name',
            field=models.CharField(max_length=50, verbose_name='商品名称'),
        ),
    ]
