# Generated by Django 2.1.1 on 2019-08-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0010_auto_20190819_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_code',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='商品二维码'),
        ),
    ]
